config/routes.rb
GoFixSomething::Application.routes.draw do
  resources :ideas do
    member do
      patch :vote
      patch :promote
    end

    resources :comments, except: [:index, :show, :new]
  end

  devise_for :users

  root to: 'high_voltage/pages#show', id: 'home'
end

app/models/comment.rb
class Comment
  include Mongoid::Document

  field :text, type: String
  field :author_id, type: Moped::BSON::ObjectId
  embedded_in :idea

  validates_presence_of :text
  validates_presence_of :author_id

  delegate :email, to: :author, prefix: true, allow_nil: true

  def author
    User.find(author_id) if author_id
  end

  def author=(user)
    self.author_id = user.try(:id)
  end
end

app/models/idea.rb
class Idea
  include Mongoid::Document
  include AASM

  field :text, type: String
  field :upvoters, type: Array, default: []
  field :downvoters, type: Array, default: []
  field :aasm_state, type: String

  belongs_to :user
  embeds_many :comments

  validates_presence_of :user
  validates_presence_of :text

  delegate :email, to: :user, prefix: true, allow_nil: true

  aasm do
    state :suggestion, initial: true
    state :project

    event :promote do
      transitions from: :suggestion, to: :project
    end
  end

  def upvote(user)
    downvoters.delete(user.id)
    upvoters.push(user.id) unless upvoters.include? user.id
    self
  end

  def upvote!(user)
    upvote(user)
    save!
  end

  def downvote(user)
    upvoters.delete(user.id)
    downvoters.push(user.id) unless downvoters.include? user.id
    self
  end

  def downvote!(user)
    downvote(user)
    save!
  end

  def cancel_vote(user)
    upvoters.delete(user.id)
    downvoters.delete(user.id)
    self
  end

  def cancel_vote!(user)
    cancel_vote(user)
    save!
  end

  def vote_total
    upvoters.length - downvoters.length
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include InheritedResources::DSL
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  actions :all, except: [:index, :show, :new]
  belongs_to :idea
  respond_to :html, :json
  decorates_assigned :comment

  private

  def permitted_params
    params.permit(comment: [:text, :author_id])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < InheritedResources::Base
  respond_to :html, :json
  decorates_assigned :idea

  custom_actions resource: [:vote, :promote]

  def vote
    vote! do |format|
      case params[:type]
      when 'up'     then @idea.upvote!(current_user)
      when 'down'   then @idea.downvote!(current_user)
      when 'cancel' then @idea.cancel_vote!(current_user)
      end

      format.html { redirect_to :back }
      format.json { render json: { vote_total: @idea.vote_total } }
    end
  end

  def promote
    promote! { @idea.promote! }
  end

  private

  def permitted_params
    params.permit(idea: [:text, :user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.map do |(type, value)|
      content_tag :div, class: ['alert-box', type], data: {alert: true} do
        h(value) + link_to(raw('&times;'), '#', class: 'close')
      end
    end.join.html_safe
  end

  def modal(id, options = {}, &block)
    options[:class] = Array(options[:class]) + ['reveal-modal']
    content_tag :div, options.reverse_merge(id: id) do
      capture(&block) + link_to(raw('&times;'), '#', class: 'close-reveal-modal')
    end
  end
end

app/views/comments/_comment.html.haml
.comment
  .author= comment.author_email
  .html= comment.html

app/views/comments/_form.html.haml
:ruby
  idea ||= @idea
  comment ||= idea.comments.new

= simple_form_for [idea, comment] do |f|
  .row
    = f.hidden_field :author_id, value: current_user.try(:id)
    .inputs.large-9.columns
      = f.input :text, as: :text, label: false
    .actions.large-3.columns
      = f.submit class: 'button expand'

app/views/ideas/_form.html.haml
= simple_form_for @idea || Idea.new do |f|
  = f.error_notification

  .inputs
    = f.input :text, as: :text, label: false, input_html: { rows: 6, style: "height:auto" }
    = f.hidden_field :user_id, value: user_signed_in? ? current_user.id : nil

  .actions
    = f.submit "Okay then, let's get started!", class: %w[button expand]

app/views/ideas/_idea.html.haml
%article.panel
  %header.clearfix
    .left
      %h6
        = idea.user_email
        = link_to '(show)', idea
    .right
      = link_to edit_idea_path(idea) do
        %i.entypo.pencil
      = link_to idea, method: :delete, data: { confirm: 'Are you sure?' } do
        %i.entypo.cross
  %hr

  .clearfix
    .voting-widget.left{ data: { idea_id: idea.id,
                                 vote_total: idea.vote_total,
                                 can_upvote: idea.can_upvote?,
                                 can_downvote: idea.can_downvote?,
                                 can_cancel_vote: idea.can_cancel_vote? } }
      (#{idea.vote_total})

    - if idea.owned_by_current_user?
      %ul.button-group.right
        %li= link_to( 'Promote',
                      promote_idea_path(idea),
                      method: 'patch',
                      data: { confirm: "Are you sure?" },
                      class: %w[tiny promote button] )

  %br

  = idea.html

app/views/ideas/edit.html.haml
%h1 Editing idea

= render 'form'

= link_to 'Show', @idea
\|
= link_to 'Back', ideas_path

app/views/ideas/index.html.haml
%h1 Listing ideas

%ul.small-block-grid-2.large-block-grid-3
  - @ideas.decorate.each do |idea|
    %li= render partial: 'idea', object: idea,
                locals: { show_links: true }

= link_to 'New Idea', new_idea_path

app/views/ideas/new.html.haml
%h1 New idea

= render 'form'

= link_to 'Back', ideas_path

app/views/ideas/show.html.haml
= render idea

%ul.no-bullet
  = render partial: 'comments/comment',
           collection: idea.comments,
           layout: 'shared/list_item'
  %li= render 'comments/form'

= link_to 'Edit', edit_idea_path(@idea)
\|
= link_to 'Back', ideas_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="author" href="humans.txt" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="row">
      <div class="small-12 columns">
        <%= flash_messages %>
      </div>
    </div>

    <div id="content" class="row">
      <div class="small-12 columns">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>

    <%= render 'shared/modals' %>
  </body>
</html>

app/views/layouts/devise.html.haml
- content_for :content do
  .large-6.push-3.column.panel
    =yield

= render template: "layouts/application"

app/views/pages/home.html.haml
.row
  .large-8.small-centered.columns
    %h3 So what do you want to do to make your city better?
    = render 'ideas/form'

app/views/shared/_list_item.html.haml
%li=yield

app/views/shared/_modals.html.haml
- unless user_signed_in?
  = modal :signUpModal, class: ['small'] do
    %h2 Sign up
    
    = simple_form_for('user', url: user_session_path) do |f|
      .form-inputs
        = f.input :email, :required => true, :autofocus => true
        = f.input :password, :required => true
        = f.input :password_confirmation, :required => true

      .form-actions
        = f.button :submit, "Sign up", class: "small expand"

    %a.close-reveal-modal &#215;

  = modal :signInModal, class: ['small'] do
    %h2 Sign in
    
    = simple_form_for('user', url: user_session_path) do |f|
      .form-inputs
        = f.input :email, :required => false, :autofocus => true
        = f.input :password, :required => false
        = f.input :remember_me, as: :boolean

      .form-actions
        = f.button :submit, 'Sign in', class: 'small expand'

    %a.close-reveal-modal &#215;

app/views/shared/_navbar.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1= link_to 'Go Fix Something!', root_path
    %li.toggle-topbar.menu-icon
      %a(href='#')
        %span Menu
  %section.top-bar-section
    %ul.right
      - if user_signed_in?
        %li
          %p Hello <em>#{current_user.email}</em>
        %li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Sign up", new_user_registration_path, data: { reveal_id: 'signUpModal' }
        %li= link_to "Sign in", new_user_session_path, data: { reveal_id: 'signInModal' }